# Aula 01: Classificando emails, animais e muito mais

## Porcos e Cachorros

In [8]:
import numpy as np
import scipy as scp
import pandas as pd
from sklearn.naive_bayes import MultinomialNB

In [9]:
porco1 = [1, 1, 0]
porco2 = [1, 1, 0]
porco3 = [1, 1, 0]
cachorro4 = [1, 1, 1]
cachorro5 = [0, 1, 1]
cachorro6 = [0, 1, 1]

dados = [porco1, porco2, porco3, cachorro4, cachorro5, cachorro6]

marcacoes = [1, 1, 1, -1, -1, -1]

from sklearn.naive_bayes import MultinomialNB

modelo = MultinomialNB()
modelo.fit(dados, marcacoes)

misterioso1 = [1, 1, 1]
misterioso2 = [1, 0, 0]
misterioso3 = [0, 0, 1]

teste = [misterioso1, misterioso2, misterioso3]

resultado = modelo.predict(teste)

print(resultado)

[-1  1 -1]


In [10]:
marcacoes_teste = [-1,1,-1]

diferencas = resultado - marcacoes_teste

acertos = [d for d in diferencas if d == 0]

total_de_acertos = len(acertos)
total_de_elementos = len(teste)

taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

print(resultado)
print(diferencas)
print(taxa_de_acerto)

[-1  1 -1]
[0 0 0]
100.0


# Aula 02: Importando, classificando e validando um modelo

In [11]:
uri = '/content/drive/MyDrive/Estudo/Data Science/Datasets/acesso.csv'
dados = pd.read_csv(uri)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Estudo/Data Science/Datasets/acesso.csv'

In [ ]:
x = dados[['acessou_home','acessou_como_funciona','acessou_contato']]
y = dados.comprou

Outra forma de leitura:
```
import csv

def carregar_acessos():
    dados = []
    marcacoes = []

    arquivo = open('acesso.csv', 'r')
    leitor = csv.reader(arquivo)

    for acessou_home, acessou_como_funciona,
    acessou_contato, comprou in leitor:

        dados.append([acessou_home, 
            acessou_como_funciona,
            acessou_contato])
        marcacoes.append(comprou)

    return dados, marcacoes

```

Lendo os dados:
```
>>> dados, marcacoes = carregar_acessos()
>>> marcacoes
>>> ['comprou', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '1', '0', '0', '0', '1', '0', '1', '1', '1', '1', '0', '0', '1', '0', '0', '0', '1', '0', '0', '1', '1', '0', '0', '0', '0', '1', '0', '1', '0', '1', '0', '1', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '1', '0', '0', '0']
>>> dados
>>> [['acessou_home', 'acessou_como_funciona', 'acessou_contato'], ['1', '1', '0'], ['1', '1', '0'], ['1', '1', '0'], ['1', '1', '0'], ['1', '1', '0'], ['1', '0', '1'], ['1', '1', '0'], ['1', '0', '1'], ['1', '1', '0'], ['1', '0', '1'], ['1', '1', '0'], ['1', '0', '1'], ['0', '0', '1'], ['0', '0', '1'], ['0', '0', '1'], ['0', '0', '1'], ['0', '0', '1'], ['0', '1', '0'], ['0', '0', '1'], ['0', '1', '0'], ['0', '0', '1'], ['0', '1', '0'], ['0', '0', '1'], ['0', '1', '0'], ['1', '0', '1'], ['1', '1', '1'], ['1', '1', '1'], ['1', '0', '1'], ['0', '1', '0'], ['0', '0', '1'], ['0', '1', '0'], ['1', '0', '1'], ['0', '0', '1'], ['1', '0', '1'], ['1', '0', '1'], ['1', '0', '1'], ['1', '0', '1'], ['0', '0', '1'], ['1', '1', '0'], ['1', '0', '1'], ['0', '1', '0'], ['0', '0', '1'], ['0', '1', '0'], ['1', '0', '1'], ['0', '0', '1'], ['0', '0', '1'], ['1', '0', '1'], ['1', '0', '1'], ['1', '1', '0'], ['1', '1', '0'], ['1', '1', '0'], ['1', '1', '0'], ['1', '0', '1'], ['1', '1', '0'], ['1', '0', '1'], ['1', '1', '0'], ['1', '0', '1'], ['1', '1', '0'], ['1', '0', '1'], ['0', '0', '1'], ['1', '0', '1'], ['0', '1', '0'], ['0', '0', '1'], ['0', '1', '0'], ['1', '0', '1'], ['0', '1', '1'], ['0', '0', '1'], ['1', '0', '1'], ['1', '0', '1'], ['1', '1', '0'], ['1', '1', '0'], ['0', '0', '1'], ['0', '0', '1'], ['0', '0', '1'], ['0', '0', '1'], ['0', '1', '0'], ['0', '0', '1'], ['0', '1', '0'], ['0', '0', '1'], ['1', '1', '0'], ['0', '0', '1'], ['0', '0', '1'], ['0', '0', '1'], ['1', '0', '1'], ['1', '0', '1'], ['1', '1', '0'], ['1', '1', '0'], ['0', '0', '1'], ['0', '0', '1'], ['1', '0', '1'], ['1', '0', '1'], ['1', '1', '0'], ['1', '1', '0'], ['0', '0', '1'], ['0', '0', '1'], ['1', '1', '1'], ['0', '0', '1'], ['0', '1', '0'], ['0', '0', '0']]
>>>
```

In [ ]:
from sklearn.naive_bayes import MultinomialNB

modelo = MultinomialNB()
modelo.fit(x,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
x_teste = [1,0,1]

In [ ]:
y_previsto = modelo.predict(x)

In [ ]:
diferencas = y_previsto - y

acertos = [d for d in diferencas if d == 0]

total_de_acertos = len(acertos)
total_de_elementos = len(y_previsto)

taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

print(total_de_elementos)
print(total_de_acertos)
print(taxa_de_acerto)

99
93
93.93939393939394


# Aula 03: Classificação de Variáveis Categóricas

Para variáveis categóricas, podemos migrar para colunas. Desta forma, realizo a discretização dos parâmetros. Exemplo:

 Para as variáveis categóricas:
*   Java
*   Algoritmos
*   Ruby

Podemos criar outras três colunas com os seguintes questionamentos:


*   Foi pesquisado Java?
*   Foi pesquisado Algoritmos?
*   Foi pesquisado Ruby?

Podemos então transformar o valor em 1 ou 0. E rodar os algoritmos de ML.











In [ ]:
clientes = pd.read_csv("https://s3.amazonaws.com/caelum-online-public/356-intro-machine-learning/busca.csv")
clientes.head()

home       busca  logado  comprou
0     0  algoritmos       1        1
1     0        java       0        1
2     1  algoritmos       0        1
3     1        ruby       1        0
4     1        ruby       0        1

In [ ]:
clientes['algoritmos'] = clientes.eval("busca == 'algoritmos'")
clientes['java'] = clientes.eval("busca == 'java'")
clientes['ruby'] = clientes.eval("busca == 'ruby'")

In [ ]:
X = clientes[['home','algoritmos','java','ruby','logado']]
Y = clientes['comprou']

In [ ]:
troca = {
    True : '1',
    False : '0'
}

In [ ]:
X.algoritmos = X.algoritmos.map(troca)
X.java = X.java.map(troca)
X.ruby = X.ruby.map(troca)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [ ]:
X.head()

home algoritmos java ruby  logado
0     0          1    0    0       1
1     0          0    1    0       0
2     1          1    0    0       0
3     1          0    0    1       1
4     1          0    0    1       0

Neste ponto, já temos os dados binários.

Vamos testar os get-dummies

In [ ]:
X_df = clientes[['home','busca','logado']]
Y_df = clientes['comprou']

In [ ]:
Xdummies_df = pd.get_dummies(X_df)
Ydummies_df = Y_df

In [ ]:
X = Xdummies_df.values
Y = Ydummies_df.values

Vamos iniciar o treino dos arquivos

In [ ]:
porcentagem_de_treino = 0.9
tamanho_de_treino = int(porcentagem_de_treino*len(Y))
tamanho_de_teste = int(len(Y) - tamanho_de_treino)
print(tamanho_de_treino,tamanho_de_teste)

900 100


In [ ]:
treino_dados = X[:tamanho_de_treino]
treino_marcacoes = Y[:tamanho_de_treino]

teste_dados = X[-tamanho_de_teste:]
teste_marcacoes = Y[-tamanho_de_teste:]

In [ ]:
from sklearn.naive_bayes import MultinomialNB
modelo = MultinomialNB()
modelo.fit(treino_dados, treino_marcacoes)

resultado = modelo.predict(teste_dados)

diferencas = resultado - teste_marcacoes

acertos = [d for d in diferencas if d == 0]
total_de_acertos = len(acertos)
total_de_elementos = len(teste_dados)

taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

print(taxa_de_acerto)
print(total_de_elementos)

82.0
100


Vamos comparar com o dummy test.

In [ ]:
len(Y)-Y.sum() # Números de 0

168

In [ ]:
Y.sum() #Números de 1

832

In [ ]:
len(Y) # Total

1000

In [ ]:
acerto_de_um = sum(Y)
acerto_de_zero = len(Y) - acerto_de_um
taxa_de_acerto_base = 100.0 * max(acerto_de_um, acerto_de_zero) / len(Y)
print("Taxa de acerto base: %.2f" % taxa_de_acerto_base)
print("Taxa de acerto do algoritmo: %.2f" % taxa_de_acerto)

# Sempre utilizar o de maior frequência
# Exemplo errado. Pois está utilizando todo o dataset

Taxa de acerto base: 83.20
Taxa de acerto do algoritmo: 82.00


In [ ]:
#Utilizando agora o teste de baseline para o teste de treino_marcacoes

acerto_de_um = sum(teste_marcacoes)
acerto_de_zero = len(teste_marcacoes) - acerto_de_um
taxa_de_acerto_base = 100.0 * max(acerto_de_um, acerto_de_zero) / len(teste_marcacoes)
print("Taxa de acerto base: %.2f" % taxa_de_acerto_base)
print("Taxa de acerto do algoritmo: %.2f" % taxa_de_acerto)

#Algoritmos com mesmo resultado
#Utilizando os dados corretos (dados de teste do dataset)

Taxa de acerto base: 82.00
Taxa de acerto do algoritmo: 82.00


#Aula 04 e 05: Naive Bayes

## Três regras de decisão principais:

**1.   Regra de Maior Chance**
        
        Sempre relacionado com a probabilidade de ser escolhida ser aquela de maior chance.

**2.   Regra de Menor Chance**

        Sempre relacionado com a probabilidade de ser escolhida ser aquela de menor chance.

**3.   Regra da Probabilidade**

        Definido como intervalos. Exemplo: de 0 a 30 (define 0), 31 a 100 (define 1)


## Variáveis Condicionais

As variáveis condicionais são variáveis que permitem computarmos probabilidades diferentes em situações diferentes, por exemplo, os clientes do Rio de Janeiro possuem a probabilidade de 68,5% de comprar e 31,5% de não comprar, porém os de São Paulo possuem 27,5% de comprar e 72,5% de não comprar. Utilizamos esses tipos de variáveis justamente para computarmos esses diferentes cenários, ou seja, as diversas probabilidades que podemos obter em nosso negócio.

## Naive Bayes

Muito utilizado, rápido e bem simples. Bastante usado para classificar textos.

https://en.wikipedia.org/wiki/Naive_Bayes_classifier

https://scikit-learn.org/stable/modules/naive_bayes.html

# Aula 06: Testando Diferentes Modelos e Validando o Melhor

## AdaBoost

In [ ]:
Xdummies_df = pd.get_dummies(X_df)
Ydummies_df = Y_df

X = Xdummies_df.values
Y = Ydummies_df.values

porcentagem_de_treino = 0.9
porcentagem_de_teste = 0.05

tamanho_de_treino = int(porcentagem_de_treino * len(Y))
tamanho_de_teste = int(porcentagem_de_teste * len(Y))
tamanho_de_validacao = len(Y) - tamanho_de_treino - tamanho_de_teste

# 0 até 799
treino_dados = X[0:tamanho_de_treino]
treino_marcacoes = Y[0  :tamanho_de_treino]

# 800 até 899
fim_de_teste = tamanho_de_treino + tamanho_de_teste
teste_dados = X[tamanho_de_treino:fim_de_teste]
teste_marcacoes = Y[tamanho_de_treino:fim_de_teste]

# 900 até 999
validacao_dados = X[fim_de_teste:]
validacao_marcacoes = Y[fim_de_teste:]

def fit_and_predict(nome, modelo, treino_dados, treino_marcacoes, teste_dados, teste_marcacoes):
	modelo.fit(treino_dados, treino_marcacoes)

	resultado = modelo.predict(teste_dados)
	acertos = (resultado == teste_marcacoes)
	total_de_acertos = sum(acertos)
	total_de_elementos = len(teste_dados)

	taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

	msg = "Taxa de acerto do algoritmo {0}: {1}".format(nome, taxa_de_acerto)

	print(msg)

	return taxa_de_acerto

from sklearn.naive_bayes import MultinomialNB
modeloMultinomial = MultinomialNB()
resultadoMultinomial = fit_and_predict("MultinomialNB", modeloMultinomial, treino_dados, treino_marcacoes, teste_dados, teste_marcacoes)

from sklearn.ensemble import AdaBoostClassifier
modeloAdaBoost = AdaBoostClassifier()
resultadoAdaBoost = fit_and_predict("AdaBoostClassifier", modeloAdaBoost, treino_dados, treino_marcacoes, teste_dados, teste_marcacoes)

if resultadoMultinomial > resultadoAdaBoost:
    vencedor = modeloMultinomial
else:
    vencedor = modeloAdaBoost

resultado = vencedor.predict(validacao_dados)
acertos = (resultado == validacao_marcacoes)
total_de_acertos = sum(acertos)
total_de_elementos = len(validacao_marcacoes)
taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

msg = "Taxa de acerto do vencedor entre os dois algoritmos no mundo real: {0}".format(taxa_de_acerto)
print(msg)

# a eficácia do algoritmo que chuta tudo um único valor
acerto_base = max(Counter(validacao_marcacoes).values())
taxa_de_acerto_base = 100.0 * acerto_base / len(validacao_marcacoes)
print("Taxa de acerto base: %f" % taxa_de_acerto_base)

total_de_elementos = len(validacao_dados)
print("Total de teste: %d" % total_de_elementos)

Taxa de acerto do algoritmo MultinomialNB: 86.0
Taxa de acerto do algoritmo AdaBoostClassifier: 88.0
Taxa de acerto do vencedor entre os dois algoritmos no mundo real: 82.0
Taxa de acerto base: 78.000000
Total de teste: 50


Percebi que o teste e treino com os parâmetros menores (utilizando uma amostra menor), obtém-se um modelo NB mais assertivo. 